### ISSUE TITLE
UserID is only of type uint.

### ISSUE THREAD

**Issue by leodahal4** [harranali/authority#10]
`
superAdmin := getFirstUser(db)
`
`
err = authority2.AssignRole(superAdmin, "SUPER-ADMIN")
`
Prompts as an error saying, 

`
Cannot use 'superAdmin' (type string) as the type uint
`

This is not **convenient**, as the **UserID** in my case is **UUID** i.e of tyoe **string**.

**Comment by harranali** [comment]
Hi @leodahal4 ,
The issue has been fixed and will be included in the next version release, user id now supports strings and other types.
Thanks.
